import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Speedbanana | Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-[calc(100vh-8rem)] flex items-center justify-center">
      {children}
    </main>
  );
}
